/**
 * faceRevealDefenseAllowlist.ts
 *
 * Curated set of recognizable NFL defensive player IDs for the Face Reveal
 * game mode. Only players whose faces an average NFL fan would know.
 * Generated by cross-referencing a top-200 defensive player list against
 * nfl_lineup_pool.json.
 */

export const DEFENSE_ALLOWLIST = new Set<string>([
  '00-0021377', // Ed Reed
  '00-0018227', // Charles Woodson
  '00-0022119', // Troy Polamalu
  '00-0025398', // Patrick Willis
  '00-0021140', // Julius Peppers
  '00-0021146', // Dwight Freeney
  '00-0000585', // Champ Bailey
  '00-0025401', // Darrelle Revis
  '00-0028092', // Richard Sherman
  '00-0021977', // Osi Umenyiora
  '00-0025433', // LaMarr Woodley
  '00-0020712', // James Harrison
  '00-0027002', // Clay Matthews
  '00-0023445', // DeMarcus Ware
  '00-0022161', // Terrell Suggs
  '00-0024341', // Elvis Dumervil
  '00-0022740', // Jared Allen
  '00-0027855', // Ndamukong Suh
  '00-0024227', // Haloti Ngata
  '00-0022712', // Vince Wilfork
  '00-0020535', // Justin Smith
  '00-0024235', // Tamba Hali
  '00-0028008', // Justin Houston
  '00-0027949', // J.J. Watt
  '00-0031364', // Jadeveon Clowney
  '00-0030459', // Tyrann Mathieu
  '00-0027866', // Earl Thomas
  '00-0027733', // Kam Chancellor
  '00-0029255', // Bobby Wagner
  '00-0028037', // K.J. Wright
  '00-0029248', // Luke Kuechly
  '00-0023448', // Thomas Davis
  '00-0027954', // Ryan Kerrigan
  '00-0026989', // Brian Orakpo
  '00-0026991', // Brian Cushing
  '00-0029669', // Dont\'a Hightower
  '00-0027647', // Devin McCourty
  '00-0027010', // Patrick Chung
  '00-0031218', // Malcolm Butler
  '00-0029542', // Stephon Gilmore
  '00-0026160', // Aqib Talib
  '00-0027940', // Von Miller
  '00-0030448', // Kawann Short
  '00-0023750', // Mario Williams
  '00-0026190', // Calais Campbell
  '00-0029585', // Chandler Jones
  '00-0029693', // Olivier Vernon
  '00-0027867', // Jason Pierre-Paul
  '00-0027885', // Linval Joseph
  '00-0030573', // Sheldon Richardson
  '00-0027968', // Muhammad Wilkerson
  '00-0029040', // Damon Harrison
  '00-0031388', // Aaron Donald
  '00-0026618', // Michael Bennett
  '00-0026232', // Cliff Avril
  '00-0032210', // Frank Clark
  '00-0033868', // Myles Garrett
  '00-0031565', // Danielle Hunter
  '00-0027701', // Everson Griffen
  '00-0029606', // Harrison Smith
  '00-0025424', // Eric Weddle
  '00-0036411', // Antoine Winfield Jr.
  '00-0032165', // Marcus Peters
  '00-0033055', // Jalen Ramsey
  '00-0033050', // Xavien Howard
  '00-0033874', // Marshon Lattimore
  '00-0030062', // Darius Slay
  '00-0029261', // Casey Hayward
  '00-0027943', // Patrick Peterson
  '00-0032262', // Landon Collins
  '00-0033872', // Jamal Adams
  '00-0034790', // Derwin James
  '00-0033890', // Budda Baker
  '00-0034675', // Jessie Bates III
  '00-0033132', // Kevin Byard
  '00-0030090', // Micah Hyde
  '00-0030114', // Jordan Poyer
  '00-0034874', // Roquan Smith
  '00-0034815', // Fred Warner
  '00-0032401', // De\'Vondre Campbell
  '00-0032109', // Kwon Alexander
  '00-0029607', // Demario Davis
  '00-0023624', // C.J. Mosley
  '00-0029562', // Lavonte David
  '00-0035707', // Devin White
  '00-0034773', // Vita Vea
  '00-0031101', // Shaquil Barrett
  '00-0034778', // Carlton Davis III
  '00-0036932', // Micah Parsons
  '00-0036361', // Trevon Diggs
  '00-0034834', // Sam Hubbard
  '00-0033935', // Trey Hendrickson
  '00-0034973', // Maxx Crosby
  '00-0032378', // DeForest Buckner
  '00-0031583', // Grady Jarrett
  '00-0036356', // Isaiah Simmons
  '00-0033875', // Haason Reddick
  '00-0034967', // Rashan Gary
  '00-0031576', // Za\'Darius Smith
  '00-0033120', // Kenny Clark
  '00-0034728', // Jaire Alexander
  '00-0037190', // Sauce Gardner
  '00-0035718', // Quinnen Williams
  '00-0035717', // Nick Bosa
  '00-0032164', // Arik Armstead
  '00-0036874', // Pat Surtain II
  '00-0034832', // Bradley Chubb
  '00-0032971', // Justin Simmons
  '00-0030106', // Chris Jones
  '00-0035713', // Brian Burns
  '00-0036220', // Derrick Brown
  '00-0037611', // Kayvon Thibodeaux
  '00-0027962', // Cameron Jordan
  '00-0026990', // Malcolm Jenkins
  '00-0032415', // Matthew Judon
  '00-0031933', // Leonard Williams
  '00-0035683', // Dexter Lawrence
  '00-0036388', // Xavier McKinney
  '00-0033878', // Adoree\' Jackson
  '00-0031360', // Kyle Van Noy
  '00-0030421', // Jamie Collins
  '00-0036231', // Kyle Dugger
]);
